import streamlit as st
import pandas as pd
import joblib
from pathlib import Path


# -----------------------------
# Page Setup
# -----------------------------
st.set_page_config(
    page_title="COVID-19 Surge Predictor",
    page_icon="🦠",
    layout="centered"
)


# -----------------------------
# Title and Instructions
# -----------------------------
st.title("🦠 COVID-19 Surge Prediction")

st.write(
    """
    This application uses wastewater surveillance data and a machine learning
    model to predict whether a region is likely to experience a COVID-19 surge
    in the following week.

    Enter the requested surveillance information below and click **Predict**
    to receive a prediction.
    """
)


# -----------------------------
# Load Model
# -----------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

MODEL_PATH = BASE_DIR / "results" / "xgboost_model.pkl"
FEATURE_PATH = BASE_DIR / "results" / "model_features.txt"


model = joblib.load(MODEL_PATH)

with open(FEATURE_PATH) as f:
    feature_names = [line.strip() for line in f]


# -----------------------------
# Input Interface
# -----------------------------

st.header("Wastewater Surveillance Information")

log10_conc_mean = st.number_input(
    "Average Wastewater Concentration (log10)",
    value=0.0
)

log10_conc_median = st.number_input(
    "Median Wastewater Concentration (log10)",
    value=0.0
)

conc_site_z_mean = st.number_input(
    "Average Site Concentration Z-Score",
    value=0.0
)


st.header("Sampling Information")

n_samples = st.number_input(
    "Number of Wastewater Samples Collected",
    min_value=1,
    value=1
)

n_sites = st.number_input(
    "Number of Wastewater Testing Sites",
    min_value=1,
    value=1
)

pct_nondetect = st.number_input(
    "Percent of Samples with Non-Detectable Levels",
    min_value=0.0,
    max_value=100.0,
    value=0.0
)


st.header("Population and Hospital Data")

pop_served = st.number_input(
    "Population Served by Wastewater System",
    min_value=0,
    value=100000
)

admits = st.number_input(
    "Current COVID-19 Hospital Admissions",
    min_value=0,
    value=0
)

coverage = st.number_input(
    "Data Coverage",
    min_value=0.0,
    max_value=1.0,
    value=1.0
)

admits_per100k = st.number_input(
    "Hospital Admissions per 100,000 People",
    min_value=0.0,
    value=0.0
)


st.header("Recent Trends")

log10_conc_lag1 = st.number_input(
    "Wastewater Concentration One Week Ago (log10)",
    value=0.0
)

log10_conc_lag2 = st.number_input(
    "Wastewater Concentration Two Weeks Ago (log10)",
    value=0.0
)

log10_conc_lag3 = st.number_input(
    "Wastewater Concentration Three Weeks Ago (log10)",
    value=0.0
)

conc_delta_1w = st.number_input(
    "One-Week Change in Concentration",
    value=0.0
)

conc_roll3 = st.number_input(
    "Three-Week Rolling Average Concentration",
    value=0.0
)


st.header("Time Information")

month = st.selectbox(
    "Month",
    list(range(1, 13))
)

epiweek_of_year = st.number_input(
    "Epidemiological Week of Year",
    min_value=1,
    max_value=53,
    value=1
)


# -----------------------------
# Prediction
# -----------------------------

st.divider()

if st.button("🔍 Predict COVID-19 Surge"):

    input_data = {
        "log10_conc_mean": log10_conc_mean,
        "log10_conc_median": log10_conc_median,
        "conc_site_z_mean": conc_site_z_mean,
        "n_samples": n_samples,
        "n_sites": n_sites,
        "pct_nondetect": pct_nondetect,
        "pop_served": pop_served,
        "admits": admits,
        "coverage": coverage,
        "admits_per100k": admits_per100k,
        "log10_conc_lag1": log10_conc_lag1,
        "log10_conc_lag2": log10_conc_lag2,
        "log10_conc_lag3": log10_conc_lag3,
        "conc_delta_1w": conc_delta_1w,
        "conc_roll3": conc_roll3,
        "month": month,
        "epiweek_of_year": epiweek_of_year
    }


    input_df = pd.DataFrame([input_data])


    # Ensure feature order matches training
    input_df = input_df[feature_names]


    prediction = model.predict(input_df)[0]

    confidence = model.predict_proba(input_df)[0][1]


    st.header("Prediction Result")


    if prediction == 1:
        st.error(
            "⚠️ The model predicts a likely COVID-19 surge next week."
        )
    else:
        st.success(
            "✅ The model predicts no COVID-19 surge next week."
        )


    st.metric(
        "Prediction Confidence",
        f"{confidence:.1%}"
    )


    st.progress(float(confidence))


# -----------------------------
# Footer
# -----------------------------

st.divider()

st.caption(
    "This prediction is generated by a machine learning model trained on "
    "wastewater surveillance data. It is intended for research and educational purposes."
)